from __future__ import annotations

import hashlib
import json
import os
from collections.abc import Sequence
from datetime import datetime, timezone
from typing import Any

import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import SQLAlchemyError

from app.core.schema_validator import SafeSchemaValidator
from app.models.audience_feature_contracts import (
    NON_ACTIVATABLE_DATA_MODES,
    SAFE_PRIVACY_STATUSES,
    CanonicalAudienceFeature,
    CanonicalFeatureSet,
    LegacySafeVectorSnapshot,
    normalize_taxonomy_value,
    parse_utc_datetime,
    stable_digest,
    validate_embedding,
)

SAFE_METADATA_FIELDS = {
    "aggregation_level",
    "audience_name",
    "bounded_count",
    "cohort_key",
    "cohort_label",
    "created_day_part",
    "dp_delta",
    "dp_epsilon",
    "dp_mechanism",
    "dp_noisy_count",
    "embedding_text",
    "grouping_columns",
    "lookback_bucket",
    "management_quality_score",
    "noisy_maid_volume",
    "primary_poi_type",
    "privacy_status",
    "quality_score",
    "search_radius_bucket",
    "sessions",
    "total_maid_volume",
    "total_observations",
    "trait_text",
    "vector_index",
    "location_name",
}


class LegacyPostgresSafeVectorReader:
    """
    Read-only bridge from the existing Postgres array-vector index.

    The legacy index already contains privacy-safe cohort metadata and
    embeddings generated by the Audience Intelligence pipeline. This reader
    never selects raw MAIDs, observations, coordinates, or credentials.
    """

    def __init__(
        self,
        database_url: str | None = None,
        *,
        engine: Engine | None = None,
    ) -> None:
        self._database_url = database_url
        self._engine_override = engine

    def load_snapshot(
        self,
        *,
        job_id: str | None = None,
    ) -> LegacySafeVectorSnapshot:
        engine = self._engine()

        with engine.connect() as connection:
            if job_id:
                model = connection.execute(
                    text(
                        """
                        SELECT
                            job_id,
                            model_info,
                            vector_count,
                            vector_dimension,
                            updated_at
                        FROM audience_vector_models
                        WHERE job_id = :job_id
                        """
                    ),
                    {"job_id": job_id},
                ).mappings().first()
            else:
                model = connection.execute(
                    text(
                        """
                        SELECT
                            job_id,
                            model_info,
                            vector_count,
                            vector_dimension,
                            updated_at
                        FROM audience_vector_models
                        ORDER BY updated_at DESC, job_id ASC
                        LIMIT 1
                        """
                    )
                ).mappings().first()

            if not model:
                raise FileNotFoundError(
                    "No legacy privacy-safe Postgres vector snapshot was found."
                )

            selected_job_id = str(model["job_id"])
            rows = connection.execute(
                text(
                    """
                    SELECT
                        vector_index,
                        trait_text,
                        location_name,
                        primary_poi_type,
                        created_day_part,
                        quality_score,
                        embedding,
                        metadata_json
                    FROM audience_vectors
                    WHERE job_id = :job_id
                    ORDER BY vector_index ASC
                    """
                ),
                {"job_id": selected_job_id},
            ).mappings().all()

            latest_source_timestamp = self._latest_source_timestamp(connection)

        if not rows:
            raise FileNotFoundError(
                "The selected legacy vector snapshot contains no vectors."
            )

        return LegacySafeVectorSnapshot(
            job_id=selected_job_id,
            model_info=dict(model.get("model_info") or {}),
            vector_count=int(model.get("vector_count") or len(rows)),
            vector_dimension=int(model.get("vector_dimension") or 0),
            indexed_at=parse_utc_datetime(model.get("updated_at")),
            latest_source_timestamp=latest_source_timestamp,
            rows=[dict(row) for row in rows],
        )

    def _latest_source_timestamp(self, connection: Any) -> datetime | None:
        try:
            row = connection.execute(
                text(
                    """
                    SELECT MAX(created_at) AS latest_source_timestamp
                    FROM public.maid_extractions
                    """
                )
            ).mappings().first()
        except SQLAlchemyError:
            return None
        return parse_utc_datetime(
            row.get("latest_source_timestamp") if row else None
        )

    def _engine(self) -> Engine:
        if self._engine_override is not None:
            return self._engine_override
        database_url = (
            self._database_url
            or os.getenv("ECHO_DATABASE_URL")
            or os.getenv("DATABASE_URL")
            or ""
        ).strip()
        if not database_url:
            raise RuntimeError(
                "Historical feature import requires ECHO_DATABASE_URL "
                "or DATABASE_URL."
            )
        if database_url.startswith("postgres://"):
            database_url = "postgresql://" + database_url[len("postgres://") :]
        return create_engine(database_url, pool_pre_ping=True)


class PostgresCanonicalFeatureAdapterService:
    """
    Convert an existing safe Postgres vector snapshot to the versioned
    canonical feature contract used by Phase 2.

    Historical data remains searchable for internal evaluation but is
    never activation-eligible, even when a timestamp appears fresh.
    """

    def __init__(
        self,
        *,
        stale_after_hours: int | None = None,
        expected_dimension: int | None = None,
        now_fn: Any = None,
    ) -> None:
        self._stale_after_hours = int(
            stale_after_hours
            or os.getenv("DATA_FRESHNESS_STALE_HOURS", "48")
        )
        self._expected_dimension = int(
            expected_dimension
            or os.getenv("PGVECTOR_DIMENSION", "384")
        )
        self._now_fn = now_fn or (lambda: datetime.now(timezone.utc))
        self._schema_validator = SafeSchemaValidator()

    def adapt(
        self,
        snapshot: LegacySafeVectorSnapshot,
        *,
        tenant_id: str,
        purpose: str,
        rights_policy_id: str,
        privacy_policy_version: str,
        source_ref: str = "postgres://legacy_safe_audience_vectors",
        source_version: str | None = None,
        data_use_mode: str = "historical_preview",
    ) -> CanonicalFeatureSet:
        clean_tenant_id = self._required_slug(tenant_id, "tenant_id")
        clean_purpose = self._required_slug(purpose, "purpose")
        clean_rights_policy_id = self._required_slug(
            rights_policy_id,
            "rights_policy_id",
        )
        clean_privacy_policy_version = self._required_slug(
            privacy_policy_version,
            "privacy_policy_version",
        )
        clean_data_use_mode = self._required_slug(
            data_use_mode,
            "data_use_mode",
        )

        if clean_data_use_mode not in NON_ACTIVATABLE_DATA_MODES:
            raise ValueError(
                "Legacy Postgres snapshots may only be imported as "
                "historical_preview or offline_evaluation."
            )

        dimension = int(snapshot.vector_dimension)
        if dimension != self._expected_dimension:
            raise ValueError(
                "Legacy snapshot dimension is incompatible with the "
                f"Phase 2 pgvector schema. Expected {self._expected_dimension}, "
                f"received {dimension}."
            )

        latest_source = parse_utc_datetime(snapshot.latest_source_timestamp)
        freshness_status = self._freshness_status(latest_source)
        source_version_value = str(source_version or snapshot.job_id).strip()
        source_fingerprint = stable_digest(
            {
                "job_id": snapshot.job_id,
                "source_version": source_version_value,
                "latest_source_timestamp": (
                    latest_source.isoformat() if latest_source else None
                ),
                "vector_count": snapshot.vector_count,
                "vector_dimension": dimension,
                "model_info": snapshot.model_info,
                "snapshot_content_digest": self._snapshot_content_digest(
                    snapshot.rows
                ),
            }
        )
        feature_set_id = "feature_set_" + source_fingerprint[:24]

        model_backend = str(
            snapshot.model_info.get("backend") or "unknown"
        ).strip()
        model_name = str(
            snapshot.model_info.get("model_name") or model_backend
        ).strip()
        model_version = str(
            snapshot.model_info.get("model_version")
            or snapshot.model_info.get("revision")
            or "legacy_snapshot"
        ).strip()

        features = []
        for position, row in enumerate(snapshot.rows):
            feature = self._adapt_row(
                row=row,
                position=position,
                tenant_id=clean_tenant_id,
                feature_set_id=feature_set_id,
                feature_set_version=1,
                expected_dimension=dimension,
                source_fingerprint=source_fingerprint,
                latest_source=latest_source,
                freshness_status=freshness_status,
                data_use_mode=clean_data_use_mode,
                purpose=clean_purpose,
            )
            features.append(feature)

        if not features:
            raise ValueError("Legacy safe vector snapshot contains no usable features.")

        return CanonicalFeatureSet(
            tenant_id=clean_tenant_id,
            feature_set_id=feature_set_id,
            version=1,
            status="ready_for_historical_preview",
            source_mode="legacy_postgres_safe_vectors",
            data_use_mode=clean_data_use_mode,
            source_ref=source_ref,
            source_version=source_version_value,
            source_fingerprint=source_fingerprint,
            source_latest_at=latest_source,
            freshness_status=freshness_status,
            stale_after_hours=self._stale_after_hours,
            model_backend=model_backend,
            model_name=model_name,
            model_version=model_version,
            embedding_dimension=dimension,
            privacy_policy_version=clean_privacy_policy_version,
            rights_policy_id=clean_rights_policy_id,
            purpose=clean_purpose,
            eligible_for_retrieval=True,
            eligible_for_activation=False,
            feature_count=len(features),
            lineage={
                "source_job_id": snapshot.job_id,
                "source_indexed_at": (
                    snapshot.indexed_at.isoformat()
                    if snapshot.indexed_at
                    else None
                ),
                "source_latest_timestamp": (
                    latest_source.isoformat() if latest_source else None
                ),
                "source_vector_count": snapshot.vector_count,
                "raw_identifiers_read": False,
                "raw_identifiers_stored": False,
                "historical_mode_activation_blocked": True,
                "transformations": [
                    "read_existing_privacy_safe_vector_metadata",
                    "validate_safe_metadata_boundary",
                    "normalize_global_taxonomy_values",
                    "assign_versioned_feature_identity",
                    "preserve_existing_safe_embedding",
                    "block_historical_activation",
                ],
            },
            features=features,
        )

    def _adapt_row(
        self,
        *,
        row: dict[str, Any],
        position: int,
        tenant_id: str,
        feature_set_id: str,
        feature_set_version: int,
        expected_dimension: int,
        source_fingerprint: str,
        latest_source: datetime | None,
        freshness_status: str,
        data_use_mode: str,
        purpose: str,
    ) -> CanonicalAudienceFeature:
        metadata = self._metadata(row)
        self._schema_validator.validate_safe_cohort_dataframe(
            pd.DataFrame([metadata]),
            context="legacy safe vector metadata",
        )

        location_name = normalize_taxonomy_value(
            row.get("location_name") or metadata.get("location_name")
        )
        poi_type = normalize_taxonomy_value(
            row.get("primary_poi_type")
            or metadata.get("primary_poi_type")
        )
        daypart = normalize_taxonomy_value(
            row.get("created_day_part")
            or metadata.get("created_day_part")
            or "all"
        )
        if not location_name or not poi_type:
            raise ValueError(
                "Canonical features require location_name and primary_poi_type."
            )

        privacy_status = normalize_taxonomy_value(
            metadata.get("privacy_status") or "safe"
        )
        privacy_safe = privacy_status in SAFE_PRIVACY_STATUSES
        rights_status = "historical_internal_only"
        cohort_size = self._cohort_size(metadata)
        quality_score = self._quality_score(row, metadata)
        embedding = validate_embedding(
            row.get("embedding") or [],
            expected_dimension=expected_dimension,
        )
        trait_text = self._trait_text(
            row=row,
            metadata=metadata,
            location_name=location_name,
            poi_type=poi_type,
            daypart=daypart,
        )
        safe_metadata = {
            key: self._json_safe(value)
            for key, value in metadata.items()
            if key in SAFE_METADATA_FIELDS
        }
        stable_feature_payload = {
            "source_fingerprint": source_fingerprint,
            "location_name": location_name,
            "primary_poi_type": poi_type,
            "created_day_part": daypart,
            "lookback_bucket": safe_metadata.get("lookback_bucket"),
            "vector_index": int(row.get("vector_index", position)),
        }
        feature_id = "feature_" + stable_digest(stable_feature_payload)[:24]

        return CanonicalAudienceFeature(
            tenant_id=tenant_id,
            feature_set_id=feature_set_id,
            feature_set_version=feature_set_version,
            feature_id=feature_id,
            location_name=location_name,
            primary_poi_type=poi_type,
            created_day_part=daypart,
            lookback_bucket=normalize_taxonomy_value(
                safe_metadata.get("lookback_bucket")
            )
            or None,
            cohort_size=cohort_size,
            quality_score=quality_score,
            privacy_status=privacy_status,
            rights_status=rights_status,
            purpose=purpose,
            source_latest_at=latest_source,
            freshness_status=freshness_status,
            data_use_mode=data_use_mode,
            eligible_for_retrieval=privacy_safe,
            eligible_for_activation=False,
            trait_text=trait_text,
            embedding=embedding,
            metadata=safe_metadata,
        )

    def _metadata(self, row: dict[str, Any]) -> dict[str, Any]:
        raw = row.get("metadata_json")
        if isinstance(raw, str):
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError as exc:
                raise ValueError("Legacy vector metadata is not valid JSON.") from exc
        elif isinstance(raw, dict):
            parsed = dict(raw)
        elif raw is None:
            parsed = {}
        else:
            raise ValueError("Legacy vector metadata must be an object.")

        merged = dict(parsed)
        for key in (
            "vector_index",
            "trait_text",
            "location_name",
            "primary_poi_type",
            "created_day_part",
            "quality_score",
        ):
            value = row.get(key)
            if value is not None:
                merged.setdefault(key, value)

        return merged

    def _freshness_status(self, latest_source: datetime | None) -> str:
        if latest_source is None:
            return "unknown"
        age_hours = max(
            (self._now_fn() - latest_source).total_seconds() / 3600,
            0.0,
        )
        return (
            "fresh"
            if age_hours <= self._stale_after_hours
            else "stale"
        )

    def _cohort_size(self, metadata: dict[str, Any]) -> int:
        for key in (
            "dp_noisy_count",
            "noisy_maid_volume",
            "total_maid_volume",
            "bounded_count",
            "sessions",
        ):
            try:
                value = round(float(metadata.get(key)))
            except (TypeError, ValueError):
                continue
            return max(value, 0)
        return 0

    def _quality_score(
        self,
        row: dict[str, Any],
        metadata: dict[str, Any],
    ) -> float:
        value = (
            metadata.get("management_quality_score")
            or metadata.get("quality_score")
            or row.get("quality_score")
            or 0.0
        )
        try:
            parsed = float(value)
        except (TypeError, ValueError):
            return 0.0
        return round(max(0.0, min(parsed, 1.0)), 6)

    def _trait_text(
        self,
        *,
        row: dict[str, Any],
        metadata: dict[str, Any],
        location_name: str,
        poi_type: str,
        daypart: str,
    ) -> str:
        candidate = str(
            row.get("trait_text") or metadata.get("trait_text") or ""
        ).strip()
        if candidate:
            return " ".join(candidate.split())
        return (
            f"location {location_name.replace('_', ' ')} "
            f"category {poi_type.replace('_', ' ')} "
            f"daypart {daypart.replace('_', ' ')}"
        )

    def _required_slug(self, value: str, label: str) -> str:
        normalized = normalize_taxonomy_value(value)
        if not normalized:
            raise ValueError(f"{label} is required.")
        return normalized

    def _json_safe(self, value: Any) -> Any:
        if value is None or isinstance(value, (str, int, float, bool)):
            return value
        if isinstance(value, dict):
            return {
                str(key): self._json_safe(item)
                for key, item in value.items()
            }
        if isinstance(value, (list, tuple)):
            return [self._json_safe(item) for item in value]
        if hasattr(value, "item"):
            return self._json_safe(value.item())
        if hasattr(value, "isoformat"):
            return value.isoformat()
        return str(value)

    def _snapshot_content_digest(
        self,
        rows: Sequence[dict[str, Any]],
    ) -> str:
        digest = hashlib.sha256()
        for position, row in enumerate(rows):
            digest.update(str(position).encode("utf-8"))
            digest.update(
                str(row.get("vector_index", position)).encode("utf-8")
            )
            metadata = row.get("metadata_json")
            if isinstance(metadata, str):
                metadata_text = metadata
            else:
                metadata_text = json.dumps(
                    metadata or {},
                    sort_keys=True,
                    separators=(",", ":"),
                    default=str,
                )
            digest.update(metadata_text.encode("utf-8"))
            embedding = np.asarray(
                row.get("embedding") or [],
                dtype=np.float64,
            )
            digest.update(embedding.tobytes(order="C"))
        return digest.hexdigest()
